FlowerMall/Controllers/FlowerBackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FlowerMall.Models;
using PagedList;

namespace FlowerMall.Controllers
{
    public class FlowerBackController : Controller
    {
        // GET: FlowerBack
        public ActionResult Login()
        {
            return View();
        }
        //登录的方法
        [HttpPost]
        public ActionResult Login(tb_FlowerAdmin admin)
        {
            var login_check = false;
            if(admin.AdminLoginName != null && admin.AdminLoginPwd != null)
            {
                var login_name = admin.AdminLoginName.Replace("'", "”");
                var login_pwd = admin.AdminLoginPwd.Replace("'", "”");
                login_name = TextFilterate(login_name);
                login_pwd = TextFilterate(login_pwd);
                using (FlowerDBEntities db = new FlowerDBEntities())
                {
                    var a = db.tb_FlowerAdmin.FirstOrDefault(x => x.AdminLoginName == login_name && x.AdminLoginPwd == login_pwd);
                    login_check = (a != null);
                }
            }
            if (login_check)
            {
                //保存session对象
                Session["AdminAK"] = admin.AdminLoginName.Replace("'", "”");
                return Content("<script>window.location.href = \"/FlowerBack/Main\"</script>");
            }
            else
            {
                return Content("<script>alert('账号密码不匹配，请检查你的输入');window.location.href = \"/FlowerBack/Login\"</script>");
            }
        }

        //简单的防注入过滤
        public string TextFilterate(string oldStr)
        {
            oldStr = oldStr.Replace("'", "’");
            oldStr = oldStr.Replace("\"", "”");
            oldStr = oldStr.Replace("\\", "0");
            oldStr = oldStr.Replace("#", "9");
            oldStr = oldStr.Replace("/", "8");
            oldStr = oldStr.Replace("*", "7");
            oldStr = oldStr.Replace(",", "6");
            oldStr = oldStr.Replace(".", "5");
            oldStr = oldStr.Replace("%", "4");
            oldStr = oldStr.Replace("^", "3");
            oldStr = oldStr.Replace("?", "2");
            oldStr = oldStr.Replace("!", "1");
            return oldStr;
        }

        public ActionResult Main()
        {
            //
            if(Session["AdminAK"] == null)
            {
                return Content("<script>window.location.href = \"/FlowerBack/Login\"</script>");
            }
            else
            {
                //后台首页查询数据
                //用户--销售商品数--本月营收额--待发货订单
                var m_Info = new MainInfo();
                using(FlowerDBEntities db = new FlowerDBEntities())
                {
                    var user = db.tb_UserInfo.Where(x => x.UserState == 0); 
                    var userAll = db.tb_UserInfo;
                    m_Info.UserNum = user.Count();
                    m_Info.UserPer = (user.Count() * 100) / userAll.Count() + "%";
                    var good = db.tb_GoodsInfo.Where(x => x.GoodState == 0);
                    var goodAll = db.tb_GoodsInfo;
                    m_Info.GoodNum = good.Count();
                    m_Info.GoodPer = (good.Count() * 100) / goodAll.Count() + "%";
                    var order = db.tb_Order.Where(x => x.OrderState == 1);
                    m_Info.OrderNum = order.Count();
                    string date = DateTime.Now.Year.ToString() + (DateTime.Now.Month < 10 ? "0" + DateTime.Now.Month.ToString() : DateTime.Now.Month.ToString());
                    var monery = db.tb_ConsumeData.Where(x => x.OrderNumber.ToString().Contains(date) && x.ConType == 0).ToList();
                    decimal? m_monery = 0.00M;
                    foreach (var item in monery)
                    {
                        m_monery += item.ConMoney;
                    }
                    m_Info.ConMoney = m_monery;
                    ViewBag.MainInfo = m_Info;
                    var good_list = db.tb_GoodsInfo.Where(x => x.GoodState == 0).OrderByDescending(x => x.GoodID).ToList();
                    ViewBag.MainGoodList = good_list;
                }
                return View();
            }
            
        }
        //退出
        public ActionResult Exit()
        {
            Session.Clear();
            return Content("<script>window.location.href = \"/FlowerBack/Login\"</script>");
        }


        //商品管理
        public ActionResult GoodInfo(string gname,int? page = 1)
        {
            if (Session["AdminAK"] == null)
            {
                return Content("<script>window.location.href = \"/FlowerBack/Login\"</script>");
            }
            else
            {
                List<tb_GoodsInfo> goods = new List<tb_GoodsInfo>();
                using (FlowerDBEntities db = new FlowerDBEntities())
                { 
                    if (gname != null && gname != "")
                    {
                        gname = gname.Replace(" ", "");  
                        goods = db.tb_GoodsInfo.Where(x => x.GoodName.Contains(gname)).ToList();
                    }
                    else
                    {
                        goods = db.tb_GoodsInfo.ToList();
                    }
                    if (goods.Count == 0)
                    {
                        goods = db.tb_GoodsInfo.Where(x => x.GoodType.Contains(gname)).ToList();
                    }
                }
                //分页
                const int pageItems = 10;
                int currentPage = (page ?? 1);      
                IPagedList<tb_GoodsInfo> pageBooks = goods.ToPagedList(currentPage, pageItems);

                MyPageList vgood = new MyPageList();
                vgood.goodlist = pageBooks;
                return View(vgood);
            }

        }
        public ActionResult GoodInfoAjax(string gname,int? page = 1)
        {
            if (Session["AdminAK"] == null)
            {
                return Content("<script>window.location.href = \"/FlowerBack/Login\"</script>");
            }
            else
            {
                List<tb_GoodsInfo> goods = new List<tb_GoodsInfo>();
                using (FlowerDBEntities db = new FlowerDBEntities())
                {                
                    if (gname != null && gname != "")
                    {
                        gname = gname.Replace(" ", "");
                        goods = db.tb_GoodsInfo.Where(x => x.GoodName.Contains(gname)).ToList();

                    }
                    else
                    {
                        goods = db.tb_GoodsInfo.ToList();
                    }
                    if (goods.Count == 0)
                    {
                        goods = db.tb_GoodsInfo.Where(x => x.GoodType.Contains(gname)).ToList();
                    }
                }
                const int pageItems = 10;         
                int currentPage = (page ?? 1);    
                IPagedList<tb_GoodsInfo> pageBooks = goods.ToPagedList(currentPage, pageItems);

                MyPageList vgood = new MyPageList();
                vgood.goodlist = pageBooks;
                return PartialView("_SearchGoodInfo", vgood);
            }
            
        }
        //商品·上架·下架
        public ActionResult GoodState(string gstate,int gid)
        {
            int count = 0;
            using (FlowerDBEntities db = new FlowerDBEntities())
            {
                if (gstate == "上架")
                {
                    var good = db.tb_GoodsInfo.FirstOrDefault(x => x.GoodID == gid);
                    good.GoodState = 0;
                    count = db.SaveChanges();
                }
                else if (gstate == "下架")
                {
                    var good = db.tb_GoodsInfo.FirstOrDefault(x => x.GoodID == gid);
                    good.GoodState = 2;
                    count = db.SaveChanges();
                }
            }
            if(count > 0)
            {
                return Content("true");
            }
            else
            {
                return Content("false");
            }
        }

        //添加商品
        public ActionResult GoodAdd()
        {
            if (Session["AdminAK"] == null)
            {
                return Content("<script>window.location.href = \"/FlowerBack/Login\"</script>");
            }
            else
            {
                return View();
            }
            
        }
        [HttpPost]
        public ActionResult GoodAdd(tb_GoodsInfo good, HttpPostedFileBase uploadFile)
        {
            using(FlowerDBEntities db = new FlowerDBEntities())
            {
                good.GoodState = 0;
                good.GoodFreight = 8;
                good.GoodMsales = 0;
                if (uploadFile != null && uploadFile.ContentLength != 0)
                {
                    string newPath = Server.MapPath("~/Images/GoodsInfo/") + uploadFile.FileName;
                    uploadFile.SaveAs(newPath);
                    good.GoodDataImg = "/Images/GoodsInfo/" + uploadFile.FileName;
                    good.GoodMainImg = "/Images/GoodsInfo/" + uploadFile.FileName;
                }
                else
                {
                    good.GoodMainImg = "/Images/GoodsInfo/good_error_1.jpg";
                    good.GoodDataImg = "/Images/GoodsInfo/good_error_1.jpg";
                }
                db.tb_GoodsInfo.Add(good);
                db.SaveChanges();
            }
            return Content("<script>alert('添加成功，即将转到首页。');window.location.href = \"/FlowerBack/Main\"</script>");

        }


        //修改商品
        public ActionResult GoodSet(int gid)
        {
            if (Session["AdminAK"] == null)
            {
                return Content("<script>window.location.href = \"/FlowerBack/Login\"</script>");
            }
            else
            {
                tb_GoodsInfo good = new tb_GoodsInfo();
                using(FlowerDBEntities db = new FlowerDBEntities())

FlowerMall/Views/FlowerBack/GoodInfo.cshtml
@using FlowerMall.Models;
@using PagedList.Mvc;
@model MyPageList

@{
    Layout = null;
}

<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>商品管理</title>
    <link href="~/Content/bs4.pop.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/umd/popper.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bs4.pop.js"></script>
    <link href="~/Content/FlowerBack/animate.css" rel="stylesheet" />
    <link href="~/Content/FlowerBack/app-style.css" rel="stylesheet" />
    <link href="~/Content/FlowerBack/icons.css" rel="stylesheet" />
    <link href="~/Content/FlowerBack/pace.min.css" rel="stylesheet" />
    <link href="~/Content/FlowerBack/sidebar-menu.css" rel="stylesheet" />
    <style>
        #search_good_name {
            width: 300px;
            height: 25px;
            background-color: rgba(255,255,255,0.2);
            border: 1px solid white;
            font-size: 14px;
            font-family: serif;
            padding-left: 5px;
            color: white;
            outline: none;
            vertical-align: top;
        }
        .search_gname_btn {
            width: 80px;
            height: 25px;
            border: 1px solid white;
            outline: none;
            margin-left: -5px;
            vertical-align: top;
            background-color: lightskyblue;
        }

        /*分页按钮区*/
        .pagination-container {
            text-align: right;
            width: 100%;
            margin: 20px 0px;
            padding-right: 3%;
        }
        .pagination{
            display:block;
        }
        .table-responsive li {
            width: 25px;
            height: 25px;
            display: inline-block;
            border: 1px solid gray;
            text-align: center;
            margin: 0px 3px;
            /*border-radius: 5px;*/
        }
    </style>
</head>
<body class="bg-theme bg-theme1">

    <!-- Start wrapper-->
    <div id="wrapper">

        <!--Start sidebar-wrapper-->
        <div id="sidebar-wrapper" data-simplebar="" data-simplebar-auto-hide="true">
            <div class="brand-logo">
                <a href="~/flowerui/index" target="_blank">
                    <img src="~/Images/花语logo.png" class="" />
                </a>
            </div>

            <ul class="sidebar-menu do-nicescrol">
                <li class="sidebar-header">花语馨苑后台管理界面</li>
                <li>
                    <a href="~/flowerback/main">
                        <i class="zmdi zmdi-view-dashboard"></i> <span>后台首页</span>
                    </a>
                </li>

                <li class="active">
                    <a href="~/flowerback/goodinfo">
                        <i class="zmdi zmdi-book-image"></i> <span>商品管理</span>
                    </a>
                </li>

                <li>
                    <a href="~/flowerback/goodadd">
                        <i class="zmdi zmdi-assignment-o"></i> <span>上架商品</span>
                    </a>
                </li>

                <li>
                    <a href="javaScript:alert('请通过[商品管理]页面来修改商品');">
                        <i class="zmdi zmdi-grid"></i> <span>修改商品</span>
                    </a>
                </li>

                <li>
                    <a href="~/flowerback/orderinfo">
                        <i class="zmdi zmdi-calendar-check"></i> <span>订单管理</span>
                        <small class="badge float-right badge-light">New</small>
                    </a>
                </li>

                <li>
                    <a href="javaScript:alert('请通过[订单管理]页面来修改商品');">
                        <i class="zmdi zmdi-assignment-check"></i> <span>订单详情</span>
                    </a>
                </li>

                <li>
                    <a href="~/FlowerBack/UserInfo">
                        <i class="zmdi zmdi-account-circle"></i> <span>用户管理</span>
                    </a>
                </li>
            </ul>

        </div>
        <!--End sidebar-wrapper-->
        <!--Start topbar header-->
        <header style="        height: 60px;
        background-color: rgba(0,0,0,.2);
">
        </header>
        <!--End topbar header-->

        <div class="content-wrapper">
            <div class="container-fluid">

                @*<div class="row">
                    <div class="col-12 col-lg-4 col-xl-12">
                        <div class="card">
                            <div class="card-header">
                                <h3>热销商品</h3>
                            </div>
                            <div class="table-responsive">
                                <table class="table align-items-center">
                                    <tbody>
                                        <tr>
                                            <td><i class="fa fa-circle text-white mr-2"></i> Direct</td>
                                            <td>$5856</td>
                                            <td>+55%</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>*@

                <div class="row">
                    <div class="col-12 col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h3>商品信息</h3>
                                <div style="display: inline-block;float: right;margin-right: 50px;">
                                    <button onclick="GoodAdd()" type="button" class="btn btn-success">新增商品</button>
                                </div>
                                <div style=" margin: 10px auto;">
                                    @using (Ajax.BeginForm("GoodInfoAjax", "FlowerBack", new AjaxOptions
                                    {
                                        UpdateTargetId = "ajax_goodinfo",
                                        InsertionMode = InsertionMode.Replace
                                    }))
                                    {
                                        <input type="text" id="search_good_name" name="gname" placeholder="请输入商品名进行查询" autocomplete="off" />
                                        <button type="submit" class="search_gname_btn">搜索</button>
                                    }
                                </div>
                            </div>
                            <div class="table-responsive">
                                <table class="table align-items-center table-flush table-borderless">
                                    <thead>
                                        <tr>
                                            <th>商品名称</th>
                                            <th>商品图片</th>
                                            <th>商品单价</th>
                                            <th>商品库存</th>
                                            <th>商品总销量</th>
                                            <th>操作</th>
                                        </tr>
                                    </thead>
                                    <tbody id="ajax_goodinfo">
                                        @foreach (var item in Model.goodlist)
                                        {
                                            <tr>
                                                <td style="width:300px;">@item.GoodName</td>
                                                <td><img src="@item.GoodMainImg" style="width:120px;height:120px;" /></td>
                                                <td>￥@item.GoodPrice</td>
                                                <td>@item.GoodStock</td>
                                                <td>@item.GoodMsales</td>
                                                <td style="width:400px;">
                                                    <button type="button" class="btn btn-info" style="margin-right:20px;" onclick="GoodSet(@item.GoodID)">修改信息</button>
                                                    @if (item.GoodState == 2)
                                                    {
                                                        <button type="button" class="btn btn-success" onclick="GoodUp(@item.GoodID)">重新上架</button>
                                                    }
                                                    else
                                                    {
                                                        <button type="button" class="btn btn-danger" onclick="GoodDel(@item.GoodID)">下架商品</button>
                                                    }
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                                @Html.PagedListPager(Model.goodlist, page => Url.Action("GoodInfo", new { page }))
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <script>
        function GoodAdd() {
            window.location.href = "/flowerback/goodadd";
        }
        function GoodSet(id) {
            window.location.href = "/flowerback/goodset?gid=" + id;
        }
        function GoodUp(id) {
            var req = confirm("确定要重新上架该商品吗？");
            if (req) {
                //alert(id);
                $.ajax({
                    url: '/flowerback/goodstate',
                    type:"post",
                    data: { "gstate":"上架", "gid": id },
                    success: function (result) {
                        if (result == "true") {
                            alert('商品已上架');
                            location.reload(true);
                        }
                    }
                });
            }
        }
        function GoodDel(id) {
            var req = confirm("确定要下架该商品吗？");
            if (req) {
                //alert(id);
                $.ajax({
                    url: '/flowerback/goodstate',
                    type:"post",
                    data: { "gstate":"下架", "gid": id },
                    success: function (result) {
                        if (result == "true") {
                            alert('商品已下架');
                            location.reload(true);
                        }
                    }
                });
            }
        }
    </script>
</body>
</html>

FlowerMall/Views/FlowerBack/OrderInfo.cshtml
@using FlowerMall.Models;
@using PagedList.Mvc;
@model MyPageList

@{
    Layout = null;
}

<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>订单管理</title>
    <link href="~/Content/bs4.pop.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/umd/popper.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bs4.pop.js"></script>
    <link href="~/Content/FlowerBack/animate.css" rel="stylesheet" />
    <link href="~/Content/FlowerBack/app-style.css" rel="stylesheet" />
    <link href="~/Content/FlowerBack/icons.css" rel="stylesheet" />
    <link href="~/Content/FlowerBack/pace.min.css" rel="stylesheet" />
    <link href="~/Content/FlowerBack/sidebar-menu.css" rel="stylesheet" />
    <style>
        #search_good_name {
            width: 300px;
            height: 25px;
            background-color: rgba(255,255,255,0.2);
            border: 1px solid white;
            font-size: 14px;
            font-family: serif;
            padding-left: 5px;
            color: white;
            outline: none;
            vertical-align: top;
        }

        .search_gname_btn {
            width: 80px;
            height: 25px;
            border: 1px solid white;
            outline: none;
            margin-left: -5px;
            vertical-align: top;
            background-color: lightskyblue;
        }

        /*分页按钮区*/
        .pagination-container {
            text-align: right;
            width: 100%;
            margin: 20px 0px;
            padding-right: 3%;
        }

        .pagination {
            display: block;
        }

        .table-responsive li {
            width: 25px;
            height: 25px;
            display: inline-block;
            border: 1px solid gray;
            text-align: center;
            margin: 0px 3px;
            /*border-radius: 5px;*/
        }

        #float_area {
            width: 100%;
            height: 100%;
            background-color: rgba(255, 255, 255, 0.3);
            position: fixed;
            /* display: none; */
            top: 0;
            transition: all linear .6s;
            z-index: 999;
        }
    </style>
</head>
<body class="bg-theme bg-theme1">

    <!-- Start wrapper-->
    <div id="wrapper">

        <!--Start sidebar-wrapper-->
        <div id="sidebar-wrapper" data-simplebar="" data-simplebar-auto-hide="true">
            <div class="brand-logo">
                <a href="~/flowerui/index" target="_blank">
                    <img src="~/Images/花语logo.png" class="" />
                </a>
            </div>

            <ul class="sidebar-menu do-nicescrol">
                <li class="sidebar-header">花语馨苑后台管理界面</li>
                <li>
                    <a href="~/flowerback/main">
                        <i class="zmdi zmdi-view-dashboard"></i> <span>后台首页</span>
                    </a>
                </li>

                <li>
                    <a href="~/flowerback/goodinfo">
                        <i class="zmdi zmdi-book-image"></i> <span>商品管理</span>
                    </a>
                </li>

                <li>
                    <a href="~/flowerback/goodadd">
                        <i class="zmdi zmdi-assignment-o"></i> <span>上架商品</span>
                    </a>
                </li>

                <li>
                    <a href="javaScript:alert('请通过[商品管理]页面来修改商品');">
                        <i class="zmdi zmdi-grid"></i> <span>修改商品</span>
                    </a>
                </li>

                <li class="active">
                    <a href="~/flowerback/orderinfo">
                        <i class="zmdi zmdi-calendar-check"></i> <span>订单管理</span>
                        <small class="badge float-right badge-light">New</small>
                    </a>
                </li>

                <li>
                    <a href="javaScript:alert('请通过[订单管理]页面来修改商品');">
                        <i class="zmdi zmdi-assignment-check"></i> <span>订单详情</span>
                    </a>
                </li>

                <li>
                    <a href="~/FlowerBack/UserInfo">
                        <i class="zmdi zmdi-account-circle"></i> <span>用户管理</span>
                    </a>
                </li>
            </ul>

        </div>
        <header style="height: 60px; background-color: rgba(0,0,0,.2);"></header>

        <div class="content-wrapper">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-12 col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h3>订单信息</h3>
                                <div style=" margin: 10px auto;">
                                    @using (Ajax.BeginForm("OrderInfoAjax", "FlowerBack", new AjaxOptions
                                    {
                                        UpdateTargetId = "ajax_orderinfo",
                                        InsertionMode = InsertionMode.Replace
                                    }))
                                    {
                                        <input type="text" id="search_good_name" name="ordernum" placeholder="请输入订单标号进行查询" autocomplete="off" />
                                        <button type="submit" class="search_gname_btn">搜索</button>
                                    }
                                </div>
                            </div>
                            <div class="table-responsive">
                                <table class="table align-items-center table-flush table-borderless">
                                    <thead>
                                        <tr>
                                            <th>订单编号</th>
                                            <th>订单总金额</th>
                                            <th>付款时间</th>
                                            <th>完成时间</th>
                                            <th>订单状态</th>
                                            <th>操作</th>
                                        </tr>
                                    </thead>
                                    <tbody id="ajax_orderinfo">
                                        @foreach (var item in Model.orderlist)
                                        {
                                            <tr>
                                                <td>@item.OrderNumber</td>
                                                <td>@item.OrderMoney</td>
                                                <td>@item.PaymentTime</td>
                                                @if(item.ReceiveTime == null)
                                                {
                                                    <td>交易暂未完成</td>
                                                }
                                                else
                                                {
                                                    <td>@item.ReceiveTime</td>
                                                }
                                                @if (item.OrderState == 1)
                                                {
                                                    <td style="color:orange;">待发货·请尽快发货</td>
                                                }else if(item.OrderState == 2)
                                                {
                                                    <td>正在运输中</td>
                                                }else if(item.OrderState == 3)
                                                {
                                                    <td>已确认收货，待评价</td>
                                                }else if(item.OrderState == 4)
                                                {
                                                    <td style="color:greenyellow;">交易完成</td>
                                                }
                                                <td>
                                                    <button class="btn btn-success" onclick="Details(@item.OrderID)">查看详情</button>
                                                </td>
                                            </tr>
                                        }

                                    </tbody>
                                </table>
                                @Html.PagedListPager(Model.orderlist, page => Url.Action("OrderInfo", new { page }))
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <script>
        function Details(id) {
            window.location.href = "/flowerback/OrderDetails?oid=" + id;
        }

    </script>
</body>
</html>

FlowerMall/Views/FlowerBack/_SearchGoodInfo.cshtml
@using FlowerMall.Models;
@using PagedList.Mvc;
@model MyPageList


@foreach (var item in Model.goodlist)
{
    <tr>
        <td style="width:300px;">@item.GoodName</td>
        <td><img src="@item.GoodMainImg" style="width:120px;height:120px;" /></td>
        <td>￥@item.GoodPrice</td>
        <td>@item.GoodStock</td>
        <td>@item.GoodMsales</td>
        <td style="width:400px;">
            <button type="button" class="btn btn-info" style="margin-right:20px;" onclick="GoodSet(@item.GoodID)">修改信息</button>
            @if (item.GoodState == 2)
            {
                <button type="button" class="btn btn-success" onclick="GoodUp(@item.GoodID)">重新上架</button>
            }
            else
            {
                <button type="button" class="btn btn-danger" onclick="GoodDel(@item.GoodID)">下架商品</button>
            }
        </td>
    </tr>
}

FlowerMall/Views/FlowerBack/_SearchOrderInfo.cshtml
@using FlowerMall.Models;
@using PagedList.Mvc;
@model MyPageList

@foreach (var item in Model.orderlist)
{
    <tr>
        <td>@item.OrderNumber</td>
        <td>@item.OrderMoney</td>
        <td>@item.PaymentTime</td>
        @if (item.ReceiveTime == null)
        {
            <td>交易暂未完成</td>
        }
        else
        {
            <td>@item.ReceiveTime</td>
        }
        @if (item.OrderState == 1)
        {
            <td style="color:orange;">待发货·请尽快发货</td>
        }
        else if (item.OrderState == 2)
        {
            <td>正在运输中</td>
        }
        else if (item.OrderState == 3)
        {
            <td>已确认收货，待评价</td>
        }
        else if (item.OrderState == 4)
        {
            <td style="color:greenyellow;">交易完成</td>
        }
        <td>
            <button class="btn btn-success" onclick="Details(@item.OrderID)">查看详情</button>
        </td>
    </tr>
}