FlowerMall/Controllers/FlowerUIController.cs
using FlowerMall.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FlowerMall.Controllers
{
    public class FlowerUIController : Controller
    {
        // GET: FlowerUI
        public ActionResult Index()
        {
            List<tb_GoodsInfo> Lovegoods;//爱情鲜花
            List<tb_GoodsInfo> Affegoods;//亲情鲜花
            using (FlowerDBEntities db = new FlowerDBEntities())
            {
                Lovegoods = db.tb_GoodsInfo.Where(x => x.GoodType.Contains("爱情") && x.GoodState != 2).ToList();
                Affegoods = db.tb_GoodsInfo.Where(x => x.GoodType.Contains("亲情") && x.GoodState != 2).ToList();
            }
            ViewBag.LoveInfo = Lovegoods;
            ViewBag.AffeInfo = Affegoods;
            return View();
        }

        //登录
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(tb_UserInfo myuser,string yzm)
        {
            if(Session["yzmcode"].ToString()  != yzm.ToLower())
                {
                    return Content("notcode");
                }
            tb_UserInfo user;
            //执行数据库验证
            using (FlowerDBEntities db = new FlowerDBEntities())
            {
                user = db.tb_UserInfo.FirstOrDefault(m => m.UserLoginName == myuser.UserLoginName && m.UserLoginPwd == myuser.UserLoginPwd);

                if (user != null)
                {
                    //判断账号情况
                    int ustate = Convert.ToInt32(user.UserState);
                    if (ustate != 0)
                    {
                        if (ustate == 2)
                        {
                            //永久封停
                            return Content("forever");
                        }
                        else if (ustate == 1)
                        {
                            //被冻结，判断解封时间
                            DateTime seal = Convert.ToDateTime(user.SealTime);
                            DateTime nowTime = DateTime.Now;
                            if (seal > nowTime)
                            {
                                return Content("nologin");
                            }
                            else
                            {
                                //到达解封时间，修改用户状态
                                user.UserState = 0;
                                db.SaveChanges();
                                Session["username"] = user.UserName.Length > 0 ? user.UserName : "请设置昵称";
                                return Content("true");
                            }
                        }
                        else
                        {
                            return Content("forever");
                        }
                    }
                    Session["username"] = user.UserName.Length > 0 ? user.UserName : "请设置昵称";
                    Session["userid"] = user.UserID;
                    return Content("true");
                }
                else
                {
                    return Content("false");
                }
            }
        }


        //注册
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(tb_UserInfo user, HttpPostedFileBase uploadFile)
        {
            using(FlowerDBEntities db = new FlowerDBEntities())
            {
                var u = db.tb_UserInfo.FirstOrDefault(x => x.UserLoginName == user.UserTel);
                if (u == null)
                {
                    //判断文件是否存在
                    if (uploadFile != null && uploadFile.ContentLength != 0)
                    {
                        //拼接路径
                        string newPath = Server.MapPath("~/Images/userhead/") + uploadFile.FileName;
                        //保存文件
                        uploadFile.SaveAs(newPath);
                        //保存文件名至数据库
                        user.UserImg = "/Images/UserHead/" + uploadFile.FileName;
                    }
                    else
                    {
                        user.UserImg = "/Images/UserHead/headimg_def1.jpg";
                    }
                    user.UserLoginName = user.UserTel;
                    user.UserDatetime = DateTime.Now;
                    db.tb_UserInfo.Add(user);
                    db.SaveChanges();

                    var n = db.tb_UserInfo.FirstOrDefault(x => x.UserLoginName == user.UserLoginName);
                    Session["username"] = n.UserName;
                    Session["userid"] = n.UserID;

                    return Content("<script>alert('注册成功，即将转到首页。');window.location.href = \"/FlowerUI/Index\"</script>");
                }
                else
                {
                    return Content("<script>alert('该账号已存在。');window.location.href = \"/FlowerUI/Register\"</script>");
                }
            }
        }

        //退出
        public ActionResult Exit()
        {
            //清除Session对象
            Session.Clear();
            //Session.Remove("UserID");
            //返回首页
            return Content("<script>window.location.href = \"/FlowerUI/Index\"</script>");
        }


        //详情页
        public ActionResult Details(int id,int? page = 1)
        {
            tb_GoodsInfo good = new tb_GoodsInfo();
            List<tb_GoodsInfo> goodlist = new List<tb_GoodsInfo>();
            List<tb_ReceAddress> rece = new List<tb_ReceAddress>();
            List<tb_Comments> comm = new List<tb_Comments>();
            using(FlowerDBEntities db = new FlowerDBEntities())
            {
                //商品详情信息
                good = db.tb_GoodsInfo.FirstOrDefault(x => x.GoodID == id && x.GoodState != 2);
                //商品评价信息
                comm = db.tb_Comments.Where(x => x.GoodID == id).OrderByDescending(m => m.CommTime).ToList();
                //推荐商品信息
                Random rd = new Random();
                //查询所有在售商品id
                int[] idl = db.tb_GoodsInfo.Where(x => x.GoodState == 0).Select(a => a.GoodID).ToArray();
                for (int i = 0; i < 5; i++)
                {
                    //通过生成随机数的方式，获取数组内随机商品id
                    var ss = idl[rd.Next(0, idl.Length)];
                    //根据随机id查询不同的商品，并填充到List<T>中
                    var rec = db.tb_GoodsInfo.FirstOrDefault(x => x.GoodID == ss);
                    goodlist.Add(rec);
                }
                ViewBag.recogood = goodlist;

                if (Session["userid"] != null)
                {
                    
                    var uid = int.Parse(Session["userid"].ToString());
                    //用户收货地址
                    rece = db.tb_ReceAddress.Where(x => x.UserID == uid).ToList();
                    ViewBag.UserRece = rece;
                }
                if (good == null)
                {
                    return Content("<script>alert('该商品不存在或已下架。');window.location.href = \"/FlowerUI/Index\"</script>");
                }
            }
            ViewBag.gooddata = good;
            //分页
            const int pageItems = 5;            //每页显示的数据
            int currentPage = (page ?? 1);      //当前页码
            IPagedList<tb_Comments> pageBooks = comm.ToPagedList(currentPage, pageItems);

            MyPageList vgood = new MyPageList();
            vgood.commlist = pageBooks;
            //ViewBag.commlist = vgood.commlist;
            return View(vgood);
            //return View(good);
        }

        //查询收货地址
        public ActionResult SelUserRece(int rid)
        {
            string srece = "";
            using(FlowerDBEntities db = new FlowerDBEntities())
            {
                var rece = db.tb_ReceAddress.FirstOrDefault(x => x.ReceID == rid);
                srece += rece.ReceName + "^" + rece.ReceTel + "^" + rece.ReceAddr;
            }
            return Content(srece);
        }

        //加入购物车
        public ActionResult InsertShop(int gid,int gnum)
        {
            if (Session["userid"] == null) {
                return Content("未登录");
            }
            else
            {
                var uid = int.Parse(Session["userid"].ToString());
                tb_ShopCart cart = new tb_ShopCart();
                tb_GoodsInfo good;
                int count = 0;
                using (FlowerDBEntities db = new FlowerDBEntities())
                {
                    //查询当前商品信息
                    good = db.tb_GoodsInfo.FirstOrDefault(x => x.GoodID == gid);
                    //判断库存
                    int kc = int.Parse(good.GoodStock.ToString());
                    if (kc > 0 && gnum <= kc)
                    {
                        //判断购物车是否拥有该商品
                        var req = db.tb_ShopCart.FirstOrDefault(x => x.GoodID == gid && x.UserID == uid);
                        if (req == null)
                        {

                            //填充购物车信息
                            cart.UserID = uid;
                            cart.GoodID = gid;
                            cart.GoodName = good.GoodName;
                            cart.GoodPrice = good.GoodPrice;
                            cart.GoodNum = gnum;
                            cart.GoodImg = good.GoodMainImg;
                            cart.GoodInfo = good.FlowerLanguage;
                            //保存到数据库
                            db.tb_ShopCart.Add(cart);
                        }
                        else
                        {
                            req.GoodNum += gnum;
                        }

                        count = db.SaveChanges();
                    }
                    else
                    {
                        return Content("无库存");
                    }
                }
                if (count > 0)
                {
                    return Content("true");
                }
                else
                {

FlowerMall/Views/FlowerUI/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Main_body.cshtml";

    <link href="~/Content/FlowerUI/mainpage.css" rel="stylesheet" />
    <link href="~/Content/FlowerUI/Search_Top.css" rel="stylesheet" />
}

<div class="Main-container">

    <div>
        <div class="tool_logo">
            <a href="/FlowerUI/Index" title="花语首页，最美的花和最美的你">
                <img src="~/Images/花语logo.png" />
            </a>
        </div>
        <div class="tool_search">
            <form action="/flowerui/Search">
                <div class="Search_Area">
                    <input type="text" name="spname" class="Search_Input" placeholder="请输入商品名" />
                    <button class="Search_Button">搜索</button>
                </div>
            </form>
        </div>

        <div class="tool_but">

        </div>

    </div>

    @*<div>
        <input type="text" id="user_area" />
        <button onclick="mapajax()">测试</button>
    </div>*@

    @*标题*@
    <a class="main_href" href="~/flowerui/Search?spname=爱情">爱情鲜花</a> <span>&nbsp;|&nbsp;送·让你怦然心动的人</span>
    <div class="main_Item">
        @*左边*@
        <div class="container_left">
            <a href="~/flowerui/Search?spname=爱情">
                <img height="100%;" src="~/Images/GoodsInfo/lovemain.jpg" />
            </a>
        </div>
        @*右边*@
        <div class="container_right">
            @*循环部分*@
            @for (int i = 0; i < ViewBag.LoveInfo.Count && i < 8; i++)
            {
                <a href="/FlowerUI/details/@ViewBag.LoveInfo[i].GoodID">
                    <div class="contRight_Item">
                        <div style="width: 200px;height: 250px;margin: 0px auto;overflow:hidden">
                            <img style="width:250px;height:250px;margin-left: -25px;" src="@ViewBag.LoveInfo[i].GoodMainImg" />
                        </div>
                        <br />
                        <span class="con_goodname">@Html.Raw(ViewBag.LoveInfo[i].GoodName)</span>
                        <span>@ViewBag.LoveInfo[i].GoodPrice</span>
                    </div>
                </a>
            }
        </div>
    </div>

    <a class="main_href" href="~/flowerui/Search?spname=亲情">亲情鲜花</a> <span>&nbsp;|&nbsp;赠·令你值的感恩的人</span>
    <div class="main_Item">
        @*左边*@
        <div class="container_left">
            <a href="~/flowerui/Search?spname=亲情">
                <img height="100%;" src="~/Images/GoodsInfo/affemain.png" />
            </a>
        </div>
        @*右边*@
        <div class="container_right">
            @*循环部分*@
            @for (int i = 0; i < ViewBag.AffeInfo.Count && i < 8; i++)
            {
                <a href="/FlowerUI/details/@ViewBag.AffeInfo[i].GoodID">
                    <div class="contRight_Item">
                        <div style="width: 200px;height: 250px;margin: 0px auto;overflow:hidden">
                            <img style="width:250px;height:250px; margin-left: -25px;" src="@ViewBag.AffeInfo[i].GoodMainImg" />
                        </div>
                        <br />
                        <span class="con_goodname">@Html.Raw(ViewBag.AffeInfo[i].GoodName)</span>
                        <span>@ViewBag.AffeInfo[i].GoodPrice</span>
                    </div>
                </a>
            }
        </div>
    </div>

</div>

<script type="text/javascript" src="https://api.map.baidu.com/api?v=2.0&ak=这里输入AK"></script>
<script>
    function mapajax() {
        //alert("准备执行ajax")
        var area = $("#user_area").val();
        var sarea = encodeURIComponent(area);
        var httpUrl = 'https://api.map.baidu.com/geocoding/v3/?address=' + sarea + '&output=json&ak=这里输入AK&callback=showLocation';
        $.ajax({
            url: httpUrl,
            type: "get",
            contentType: "application/json",
            dataType:"JSONP",
            async: true,
            success: function (msg) {
                console.log(msg);
                //var jsonstr = JSON.stringify(msg);
                //console.log(jsonstr);
                alert(area +'的坐标信息如下：\n经度为' + msg.result.location.lng +'\n维度为' + msg.result.location.lat);
                
            }, error: function (data) {
                alert("Ajax执行失败");
                console.log(data);
            }
        })

    }

</script>

FlowerMall/Views/FlowerUI/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/FlowerUI/login.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <title>欢迎登录━(*｀∀´*)ノ亻!</title>
</head>
<body>
    <div class="top center">
        <div class="logo center">
            <a href="/flowerUI/index" title="花语首页">
                <img style="padding-top: 20px;" src="~/Images/花语logo.png" />
            </a>
        </div>
    </div>
    <div class="login" style="width:80%;margin:80px auto;display:flex;">
        <div class="login_img" style="width:70%;float:left;overflow:hidden">
            <img style="width:100%;height:100%;" src="~/Images/login_main.jpg" />
        </div>
        <div class="login_center" style="/*width:80%;*/ float: right;">
            <div class="login_top">
                <div class="left fl">会员登录</div>
                <div class="right fr">您还不是我们的会员？<a href="~/FlowerUI/register" target="_self">立即注册</a></div>
                <div class="clear"></div>
                <div class="xian center"></div>
            </div>
            <div class="login_main center">
                <div class="username">手机号:&nbsp;<input class="shurukuang" type="text" id="username" maxlength="11" name="username" placeholder="请输入你的手机号" /></div>
                <div class="username">密&nbsp;&nbsp;&nbsp;&nbsp;码:&nbsp;<input class="shurukuang" type="password" id="password" name="password" placeholder="请输入你的密码" /></div>
                <div class="username">
                    <div class="left fl">验证码:&nbsp;<input id="yzcode" class="yanzhengma" type="text" name="yzm" placeholder="请输入验证码" maxlength="4"/></div>
                    <div class="right fl">
                        <a onclick="ShuaXin()"><img id="yzCode" src="~/yzCode.ashx"/></a>
                        
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
            <div class="login_submit">
                <input class="submit" type="button" name="loginCheck" onclick="checkLogin()" value="立即登录">
            </div>
        </div>
    </div>
    <footer style="position: fixed;bottom: 0;">
        <div class="copyright">简体 | 繁体 | English | 常见问题</div>
        <div class="copyright">Flower版权所有-京ICP备10046444- 京公网安备11010802020134号-京ICP证110507号</div>

    </footer>
    <script>
        function checkLogin() {
            var username = $("#username").val();
            var pwd = $("#password").val();
            var yzm = $("#yzcode").val();
            if (username.length < 1) {
                alert("请输入账号");
            }
            else if (pwd.length < 1) {
                alert("请输入密码");
            }
            else if (yzm.length != 4) {
                alert("请输入验证码");
            }
            else {
                $.ajax({
                    url: "/FlowerUI/Login",
                    type: "post",
                    data: {"UserLoginName":username,"UserLoginPwd":pwd,"yzm":yzm},
                    success: function (result) {
                        console.log(result);
                        if (result == "true") {
                            //alert("登录成功");
                            window.location.href = "/FlowerUI/Index";
                        }
                        else if (result == "notcode") {
                            alert("验证码输入错误！");
                        }
                        else if (result == "forever") {
                            alert("该账号已被永久封停！");
                        }
                        else if (result == "nologin") {
                            alert("该账号已被暂时冻结！");
                        }
                        else if (result == "false") {
                            alert("账号密码不匹配，请检查您的输入");
                        }
                    }
                });
            }
        }
        function ShuaXin() {
            document.getElementById("yzCode").src = "/yzCode.ashx?code=" + Math.random();
        }
    </script>
</body>
</html>

FlowerMall/Views/FlowerUI/Search.cshtml
@using FlowerMall.Models;
@using PagedList.Mvc;
@model MyPageList

@{
    ViewBag.Title = "最美的花，送最美的你";
    Layout = "~/Views/Shared/Main_body.cshtml";
    <link href="~/Content/FlowerUI/Search_Top.css" rel="stylesheet" />
    <style>
        a:hover{
            text-decoration: none;
        }


        .Ajax_Area_Search_Good_Show {
            width: 70%;
            min-height: 300px;
            border: 1px solid #ccc;
            margin: 20px auto;
        }


        /*商品展示区*/
        .contGood_Item {
            display: inline-block;
            width: calc(18% - 4px);
            text-align: center;
            line-height: 20px;
            margin: 10px 1%;
            border: 1px solid white;
            color: black;
        }
        .conGood_ItemImg {
            width: 200px;
            height: 250px;
            margin: 0px auto;
            overflow: hidden
        }

        .contGood_Item:hover {
            border: 1px solid orange;
        }
        /*商品图片*/
        .contGood_Item img {
            transition: all linear .6s;
        }

        .contGood_Item:hover img {
            transform: scale(1.2);
        }
        .contGood_Item:hover .search_con_goodname {
            
        }
        /*商品价格*/
        .search_con_goodprice {
            display: block;
            font-size: 18px;
            font-weight: 700;
            color: red;
            text-align: left;
            padding-left: 10px;
            margin: 2px 0px;
        }
        /*商品名称*/
        .search_con_goodname {
            font-size: 14px;
            height: 20px;
            line-height: 20px;
            padding-left: 10px;
            text-align: left;
            overflow: hidden;
            display: block;
            color: black;
        }


        /*商品标签*/
        .sel_lable_btn{
            width: 50px;
            height: 25px;
            border: 1px dashed gray;
            background: inherit;
            outline: none;
            color: black;
        }
        .sel_lable_btn:hover{
            width: 50px;
            height: 25px;
            border: 1px solid gray;
            background-color:white;
            outline: none;
            color: orangered;
        }
        .sel_lable_btn_re{
            width: 50px;
            height: 25px;
            border: 1px solid gray;
            background-color:white;
            outline: none;
            color: orangered;
        }
        /*分页按钮区*/
        .pagination-container {
            text-align: right;
            width: 100%;
            margin: 20px 0px;
            padding-right: 3%;
        }
        .pagination{
            display:block;
        }
        li {
            width: 30px;
            height: 30px;
            display: inline-block;
            border: 1px solid gray;
            text-align: center;
            margin: 0px 3px;
            line-height: 28px;
            /*border-radius: 5px;*/
        }
        li a {
            font-size: 18px;
            color: black;
        }
        .active {
            background: #ff0036;
            color: white;
        }
    </style>
}

<div id="top_tool_area">
    <div class="tool_logo">
        <a href="/FlowerUI/Index" title="花语首页，最美的花和最美的你">
            <img src="~/Images/花语logo.png" />
        </a>
    </div>
    <div class="tool_search">
        @*<form action="/flowerui/search" method="get">
            <div class="Search_Area">
                <input type="text" name="spname" class="Search_Input" placeholder="请输入商品名" />
                <button class="Search_Button">搜索</button>
            </div>
        </form>*@

        @*@using (Html.BeginForm("Search", "FlowerUI", FormMethod.Get))
        {
            <div class="Search_Area">
                <input type="text" name="spname" class="Search_Input" placeholder="请输入商品名" />
                <button class="Search_Button">搜索</button>
            </div>
        }*@

        @*Ajax异步刷新*@
        @using (Ajax.BeginForm("SearchAjax", "FlowerUI", new AjaxOptions
        {
            UpdateTargetId = "Ajax_Area_Search_Good_Show",
            InsertionMode = InsertionMode.Replace
        }))
        {
            <div class="Search_Area">
                <input type="text" name="spname" class="Search_Input" placeholder="请输入商品名" />
                <button type="submit" class="Search_Button">搜索</button>
            </div>
        }
    </div>

</div>
@*<div style="width: 70%; margin: 0px auto; background: ghostwhite; border: 1px solid gray; padding: 10px;">
    @using (Ajax.BeginForm("SearchAjax", "FlowerUI", new AjaxOptions
    {
        UpdateTargetId = "Ajax_Area_Search_Good_Show",
        InsertionMode = InsertionMode.Replace
    }))
    {
        <span>您是不是想找关于：</span>
        <button class="sel_lable_btn" onclick="SelLable(this)" value="亲情">家人</button>
        <input type="text" id="search_lable" name="sea_lable"/>
    }
</div>*@


<!--Ajax异步加载区域-->
<div id="Ajax_Area_Search_Good_Show" class="Ajax_Area_Search_Good_Show">

    @if (Model.goodlist.Count > 0)
    {
        foreach (var item in Model.goodlist)
        {
            <a href="/FlowerUI/details/@item.GoodID">
                <div class="contGood_Item">
                    <div class="conGood_ItemImg">
                        <img style="width: 200px; height: 250px;" src="@item.GoodMainImg" />
                    </div>
                    <br />
                    <span class="search_con_goodprice">￥@item.GoodPrice</span>
                    <span class="search_con_goodname">@item.GoodName</span>
                </div>
            </a>
        }
        @Html.PagedListPager(Model.goodlist, page => Url.Action("Search", new { page }))
    }
    else
    {
        <span>未找到指定的商品</span>
    }
</div>

<script>
    function SelLable(obj) {
        var lab = obj.value;
        obj.class = "sel_lable_btn_re";
        //alert(lab);
        $("#search_lable").val(lab);
    }
</script>

FlowerMall/Views/FlowerUI/_OrderAjax.cshtml
@using FlowerMall.Models;

@foreach (var item in ViewBag.uOrder as List<tb_Order>)
{
    <div class="orderItem">
        <div class="orderItem_title">
            <span style="padding:0px 10px;">@item.CreateTime</span> <span>订单号 @item.OrderNumber</span>
            <span style="float:right;padding:0 20px;"><a href="#" onclick="OrderDel('@item.OrderID','@item.OrderState')">删除订单</a></span>
        </div>
        <table style="width: 100%;">
            <!--同样动态，查询从表-->
            @{
                var inum = 0;
                foreach (var spitem in ViewBag.formOrder as List<tb_OrderSp>)
                {
                    if (spitem.OrderID == item.OrderID)
                    {
                        <tr style="font-size:14px;border-top:1px solid gray;">
                            <td class=orderItem_3>
                                <div style="float:left;margin: 0 0 10px 10px;">
                                    <img style="width:100px;height:100px;" src="@spitem.GoodImg" />
                                </div>
                                <div class="orderName">
                                    <span>@spitem.GoodName</span>
                                </div>
                            </td>
                            <td class="orderItem_2">
                                ￥@spitem.GoodPrice
                            </td>
                            <td class="orderItem_2">
                                @spitem.GoodNums
                            </td>
                            @if (inum == 0)
                            {
                                <td class="orderItem_2">
                                    <span style="font-weight:700">￥@item.OrderMoney</span>
                                    <br />
                                    <span>（含运费：￥@item.GoodFreight）</span>
                                </td>
                                <td class="orderItem_2">
                                    @if (item.OrderState == 0)
                                    {
                                        <span>暂未付款</span><br /><span><a href="#" onclick="ShowPay(@item.OrderID)">点击付款</a></span>
                                    }
                                    else if (item.OrderState == 1)
                                    {
                                        <span>等待发货</span>
                                    }
                                    else if (item.OrderState == 2)
                                    {
                                        <span>正在运输</span><br /><span><a href="/flowerui/ordermove/@item.OrderID">查看物流</a></span>
                                        <br /><br />
                                        <span><a href="/flowerui/ordercon?oid=@item.OrderID" onclick="return confirm('请确认已收到货物！')">确认收货</a></span>
                                    }
                                    else if (item.OrderState == 3)
                                    {
                                        using (Ajax.BeginForm("OrderDataAjax", "FlowerUI", new AjaxOptions
                                        {
                                            UpdateTargetId = "orderModal_Ajax",
                                            InsertionMode = InsertionMode.Replace
                                        }))
                                        {
                                            <input type="hidden" name="selectid" value="@item.OrderID" />
                                            <button type="submit" class="btn text_red" data-toggle="modal" data-target="#myModal">等待评价</button>
                                        }
                                    }
                                    else if (item.OrderState == 4)
                                    {
                                        <span>交易完成</span>
                                    }
                                </td>
                                <td class="orderItem_2">
                                    <span><a href="#" onclick="alert('这么好的花，居然有人想退款？不会吧不会吧不会吧')">申请退款</a></span>
                                    <br />
                                    <span><a onclick="ShowQR(@item.OrderID)">查看详情</a></span>
                                    <div id="QR_@item.OrderID" class="QR_Area" onclick="CloseQR(@item.OrderID)">
                                        <div>点击即可关闭</div>
                                        <img class="qr_img" src="#" />
                                        @*<img class="qr_img" src="http://qr.liantu.com/api.php?text=http://hliyi.xyz:9527/?id=@item.OrderID&fg=007bff" />*@
                                    </div>
                                </td>
                            }
                            else
                            {
                                <td class="orderItem_2">
                                </td>
                                <td class="orderItem_2">
                                </td>
                                <td class="orderItem_2">
                                </td>
                            }
                            @{inum += 1;}
                        </tr>
                    }
                }
            }
        </table>
    </div>
}

FlowerMall/Views/FlowerUI/_OrderDataAjax.cshtml
@using FlowerMall.Models;
@model List<tb_OrderSp>

<input type="hidden" value="@Model[0].OrderID" id="Order_ID" />
@for (int i = 0; i < Model.Count; i++)
{
    <div class="modalAjaxCommItem" style="margin-bottom:10px;">
        <span style="font-size:18px;">@Model[i].GoodName</span>
        <input id="CommGoodID_@i" type="hidden" value="@Model[i].GoodID" style="display:none" />
        <div>
            <img class="modalComm_img" src="@Model[i].GoodImg" />
            <textarea id="CommText_@i"  maxlength="50"  class="modalComm_text" placeholder="请输入商品评价。"></textarea>
        </div>
    </div>
}

FlowerMall/Views/FlowerUI/_SearchGood.cshtml
@using FlowerMall.Models;
@using PagedList.Mvc;
@model MyPageList

@if (Model.goodlist.Count > 0)
{
    foreach (var item in Model.goodlist)
    {
        <a href="/FlowerUI/details/@item.GoodID">
            <div class="contGood_Item">
                <div class="conGood_ItemImg">
                    <img style="width: 200px; height: 250px;" src="@item.GoodMainImg" />
                </div>
                <br />
                <span class="search_con_goodprice">￥@item.GoodPrice</span>
                <span class="search_con_goodname">@item.GoodName</span>
            </div>
        </a>
    }
    @Html.PagedListPager(Model.goodlist, page => Url.Action("Search", new { page }))
}
else
{
    <span>未找到指定的商品</span>
}